# Project Information
name: codex-simpleflow
description: 轻量、可追溯的 Codex 工作流示例与基线
tech_stack: []
key_dirs: []
env:
  database: {}

flow:
  preferences:
    timezone: UTC
    timestamp_format: YYYY-MM-DDThhmmssZ
    require_slash: true
    natural_language: true
    display:
      quiet: true
      style: narrative      # concise | narrative
      max_bullets: 0        # 每节最多要点数（0 表示禁用）
      headers: none         # minimal | none
      show_preamble: false  # 隐藏冗长执行前言
      icons: false          # 关闭图标/emoji
    execution:
      show_stdout: on-failure
      capture_logs: to-session-reports
    testing:
      auto_smoke: true
    info:
      store_reports: false   # 是否将 /cc-info 的简要备忘写入当前会话 reports
      detail: minimal        # minimal | full（默认 minimal，仅记录 IP/端口/命令等关键提示）
    retention:
      sessions:
        keep_open: 1
        keep_archives: 5
      reports:
        keep_latest: 3
  current:
    feature: null
    session_id: null
    last_task: null
    updated_at: null
    stage: Uninitialized
